# command line: main.py --config config/uav/default.yaml --work-dir work_dir/uav/csub/ctrgcn --device 0

base_lr: 0.05
batch_size: 32
config: config/uav/default.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder_uav.Feeder
ignore_weights: []
log_interval: 100
lr_decay_rate: 0.1
model: model.ctrgcn.Model
model_args:
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 155
  num_person: 2
  num_point: 17
model_saved_name: ''
nesterov: true
num_epoch: 70
num_worker: 0
optimizer: SGD
phase: train
print_log: true
save_epoch: 45
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 50
test_batch_size: 32
test_feeder_args:
  bone: false
  data_path: data/uav/test_joint_B.npy
  debug: false
  label_path: data/uav/test_label_B.npy
  p_interval:
  - 0.95
  split: test
  vel: false
  window_size: 155
train_feeder_args:
  bone: false
  data_path: data/uav/train_joint.npy
  debug: false
  label_path: data/uav/train_label.npy
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  vel: false
  window_size: 155
warm_up_epoch: 5
weight_decay: 0.0004
weights: null
work_dir: work_dir/uav/csub/ctrgcn
