work_dir: ./work_dir/uav/csub/ctrgcn

# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: data/uav/train_joint.npy
  label_path: data/uav/train_label.npy
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 155
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: data/uav/test_joint.npy
  label_path: data/uav/test_label.npy
  split: test
  window_size: 155
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.ctrgcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.05
step: [50]
warm_up_epoch: 5

# training
device: [0,1]
batch_size: 32
test_batch_size: 32
num_epoch: 70
nesterov: True
